### ISSUE TITLE
Support pgvector

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#122]
pgvector : https://github.com/pgvector/pgvector is open-source vector similarity search for Postgres

which means you should implement a vectorstore in langchaingo https://github.com/tmc/langchaingo/blob/main/vectorstores/vectorstores.go#L12 

You can host code under `kubeagi/arcadia pkg/vectorstores/pgvector`

**Comment by bjwswang** [comment]
@zqq454224016

**Comment by zqq454224016** [comment]
ok

**Comment by bjwswang** [comment]
@Abirdcfly  Please fully integrate pg in arcadia aftet this pr https://github.com/tmc/langchaingo/pull/377 got merged. 
`Chorma-go` doesn't seem to be matained very well.

**Comment by tmc** [comment]
Merged!

**Comment by bjwswang** [comment]
> Merged!

@tmc Cool! This gonna help us a lot! 🚀

**Comment by bjwswang** [comment]
@Abirdcfly  Since this pr got merged, please try to figure out how to integrate this into our project. And  we can do more contributions to help https://github.com/tmc/langchaingo/tree/main/vectorstores/pgvector much better.

**Comment by bjwswang** [comment]
- [ ] #490
