### ISSUE TITLE
Setting default vectorstore in operator configmap

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#250]
Our system needs some default configurations, the current default configurations are `systemDatasource` and `gateway` see https://github.com/kubeagi/arcadia/blob/main/deploy/charts/arcadia/templates/config.yaml  for more details.

And see https://github.com/kubeagi/arcadia/blob/main/pkg/config/config.go for how to use these config.

You need to add one more default config to setting default vectorStore.

**Comment by Abirdcfly** [comment]
@zqq454224016 pls add some comment, so that I can assiness this issue to you.

**Comment by zqq454224016** [comment]
ok
