### ISSUE TITLE
We need to do permission check in namespaced scope.  For example the user can upload/delete/list files in a dataset only when it can create/update/delete versioenddataset in that namesapce

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#251]
We need to do permission check in namespaced scope.  For example the user can upload/delete/list files in a dataset only when it can create/update/delete versioenddataset in that namesapce

_Originally posted by @bjwswang in https://github.com/kubeagi/arcadia/pull/235#discussion_r1399995303_

**Comment by dayuy** [comment]
> @dayuy pls add some comment, so that I can assign this issue to you.

Hi

**Comment by dayuy** [comment]
In my opinion, uploading/deleting files is an independent function that can be conveniently utilized in any location. Can the permission check at the outer layer? @bjwswang  @0xff-dev

**Comment by bjwswang** [comment]
tracked at #242
