### ISSUE TITLE
For versioneddataset, the bucketname should be namespace. Not hardcoded

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#252]
For versioneddataset, the bucketname should be namespace. Not hardcoded

_Originally posted by @bjwswang in https://github.com/kubeagi/arcadia/pull/235#discussion_r1400001998_

**Comment by Abirdcfly** [comment]
@dayuy pls add some comment, so that I can assign this issue to you.

**Comment by dayuy** [comment]
> @dayuy pls add some comment, so that I can assign this issue to you.

Hi！

**Comment by bjwswang** [comment]
@dayuy  can we close this issue? and @0xff-dev  any comments ?

**Comment by dayuy** [comment]
> @dayuy can we close this issue? and @0xff-dev any comments ?

@0xff-dev
