### ISSUE TITLE
Integrate Volcano as the job controller and scheduler

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#275]
For now, we use a separate python API to handle all data processing work, it's not ideally, as it'll lack the isolation and scheduling capability if there are batch of tasks to run.
1. we should move data processing logic to a separate python image, and data processing should be focus on data and related SDK, so we can use them in the notebook later.
2. Use  Volcano as the advanced job controller and scheduler, it also has some nice features to manage batch jobs.

**Comment by bjwswang** [comment]
@zqq454224016  Please https://github.com/volcano-sh/volcano

**Comment by zqq454224016** [comment]
ok

**Comment by bjwswang** [comment]
We can also use volcano as the RAG evaluation job scheduler

**Comment by bjwswang** [comment]
> We can also use volcano as the RAG evaluation job scheduler

Job scheduler:

1. Data processing (Not now,maybe v0.3.0)
2. RAG Evaluation  (Now v0.2.0)

**Comment by bjwswang** [comment]
closed as it's not in our plan.
