### ISSUE TITLE
Evaluations

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#286]
## Overall workflow 

**TO BE DEFINED**

### RAG Evaluation

@Lanture1064 @bjwswang 

Our current RAG solution flow :

1. Dataset/VersionedDataset provides source files
2. Dataprocessing process source files to QA csv with QAGenerationChain
3. Knowledgebase generates embeddings from the QA csv file to vectorstore
4. RetrievalQAChain do similarity search against knowledgebase 
5. LLM do chat with the similarity searched content as the context

Based on our research ,we decide to use this evaluation framework https://github.com/explodinggradients/ragas 

Subtasks:

- [x] Task1 #494
- [x] Task2 #495

## Evaluation Lifecycle management

@0xff-dev @bjwswang 

For definitions:

- [x] #507 

For task runner:

- [x] #508 
- [ ] Able to use Tekton(CI/CD) as evaluation runner
- [ ] Able to use volcano(a powerful batching system) as evaluation runner

For apiserver:

- [x] #565

## Overall Workflow

![evaluation_jobflow drawio](https://github.com/kubeagi/arcadia/assets/30621793/f8bb7218-3f43-42f3-8a02-0703851dbb82)

**Comment by nkwangleiGIT** [comment]
@Lanture1064 pls do further investigation.

**Comment by nkwangleiGIT** [comment]
here is another project related to evaluate:
https://github.com/promptfoo/promptfoo

**Comment by bjwswang** [comment]
![image](https://github.com/kubeagi/arcadia/assets/30621793/f4bae93d-8f3f-4f61-9b18-43dd1794a42f)
 
We have two solutions for this RAG evaluation:

### End-To-End RAG evaluation like `auto-evaluator`  https://github.com/langchain-ai/auto-evaluator

We can treat this `end-2-end evaluation` as a kubernetes job(scheduled by Volcano) which will do:

1. source file(pdf) and testdata(QA CSV file) upload (CRD Datasource) 
2. dataset/versioneddataset creation (CRD Dataset & VersionedDataset)
3. do QA dataprocessing
4. create knowledgebase and do embedding (CRD Knowledgebase)
5. Create a application with a `RetrivalQAChain`  (CRD Application)
6. Use `questions` in `testdata file`  to chat with our application and get the answers
7. Compare the answers(from Application) with the answers(from the testdata)
- we can use Embedding to genreate the similarity between these two answers.
9. Generate a complete report

Advantages:
1. Comprehensive - From the dataprocess , konwledgebase generation to the application. 
2. Flexible - User can fine-tune theire configurations and rerun the test easliy 
3. Accurate - By fine-tuning, user can know which part ( dataprocessing? knowledgebase? embedding model? llm model? llm call parameters??? )actually lead to a bad RAG. 



### Only test our application with testdata

**Comment by nkwangleiGIT** [comment]
Some other thoughts:
* 支持 Prompt 在不同 LLM 下的评估，生成测试报告
  * RAG 评估、RAG Question Generation
  * 自动生成问题，分析问题质量，过滤掉相似度不高的问题
  * 评估指标：检索评估 - Hit Rate、MRR，回答评估 - 公正性、相关性、一致性等

**Comment by bjwswang** [comment]
Subtasks:

- [ ]  generate test dataset based on our rag solution

- [ ] generate metrics by ragas evaluation with our test dataset(QA)

**Comment by bjwswang** [comment]
> Some other thoughts:
> 
> * 支持 Prompt 在不同 LLM 下的评估，生成测试报告
>   
>   * RAG 评估、RAG Question Generation
>   * 自动生成问题，分析问题质量，过滤掉相似度不高的问题
>   * 评估指标：检索评估 - Hit Rate、MRR，回答评估 - 公正性、相关性、一致性等

1. RAG问题生成这里采用数据处理服务提供的能力即可
2. ragas的指标(metrics)比较完善。 一些框架的对比可以在 https://shimo.im/docs/1d3aMzQ1wXHnwV3g

**Comment by bjwswang** [comment]
This story can be closed. For other features like support tektonci  and other llms ,we can track in individual issues.
