### ISSUE TITLE
Minio permission check solution

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#292]
Another option:
1. Create a pair of access_key & access_secret for each bucket(namespace)
    - Only have read/write permission to that bucket
2. Use the above access_key & access_secret to create a datasource for each namespace

Then when user upload files ,it :
1. get the datasource  from the namespace
2. use the access_key & access_secret to upload files

The above solutions brings a new problem:
- when and how to create the access_key * access_secret

_Originally posted by @bjwswang in https://github.com/kubeagi/arcadia/pull/284#discussion_r1403794390_

**Comment by bjwswang** [comment]
Another benefit if we use `Datasource` to authorize users to manage bucket is :

- User can use this `datasource(accesskey&access secret)`  to upload files with `mc`

**Comment by 0xff-dev** [comment]
github.com/minio/madmin-go/v3

```go
mac, err := madmin.NewWithOptions(endpoint, &madmin.Options{
		Creds:  credentials.NewStaticV4(username, password, ""),
		Secure: false,
	})
	if err != nil {
		panic(err)
	}
	policy := `{
		"Version": "2012-10-17",
		"Statement": [
		 {
		  "Effect": "Allow",
		  "Action": [
		   "s3:*"
		  ],
		  "Resource": [
		   "arn:aws:s3:::abc/**"
		  ]
		 }
		]
	   }`
	result, err := mac.AddServiceAccount(context.TODO(), madmin.AddServiceAccountReq{
		Policy: []byte(policy),
	})
```

**Comment by bjwswang** [comment]
Seems that do permission check on relevant CRDs is more simple.

**Comment by bjwswang** [comment]
Route changes to file upload
1. /versioneddataset/files
2. /model/files

**Comment by bjwswang** [comment]
Done with `cani` solution
