### ISSUE TITLE
gql oidc authentiacate failed due to token invalid

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#323]
After 8 hours , the graphql server will treat all tokens as invalid . And restart  can recover token authentication.

**Comment by nkwangleiGIT** [comment]
check if we can refresh the token if id token is expired.

**Comment by bjwswang** [comment]
Thoght we can close this issue since this most probably caused by the timezone differences between our graphql-server and oidc poroxy

**Comment by bjwswang** [comment]
Should be fixed by this [commit](https://github.com/kubeagi/arcadia/commit/42817005a7b9fb1736b29a0b24767b35d8c2801b#diff-03ab76435c8df9f88be41a2160e36b7d8514c8a04fd208d624590340c7b0dec6R84)

**Comment by bjwswang** [comment]
Fixed by https://github.com/kubeagi/arcadia/pull/355
