### ISSUE TITLE
:octocat:  Support for uploading and downloading folders

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/arcadia#376]
This current example at `graphql-server/go-server/examples` only supports the uploading and downloading of a single file, consider accomplishing the following two requirements:
- Support for uploading folders, keep the same organization in minio
- File upload problem, at present, if the file write absolute path, because there is no handling of the prefix `/`, resulting in storage failure in minio, that is to say, if the user uses the parameter `--file=/local/a.tx` , after we read the file, this path to be modified to `local/a.txt`

**Comment by dayuy** [comment]
Hi!

**Comment by nkwangleiGIT** [comment]
we also need to support subfolder for data processing, knowledge, etc ... let's do it later.

**Comment by bjwswang** [comment]
@dayuy any progress ?
