### ISSUE TITLE
Delete KnowledgeBase and create new one with the same name, run app will get 400 bad request

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#391]
Here is the error log:
```
retrievalqachain.go:90] out:, err:400 Bad Request
````
Workaround is to restart apiserver/graphql-server, seems a local cache issue that should be fixed.

**Comment by bjwswang** [comment]
This could be a bug when using chromadb.

**Comment by nkwangleiGIT** [comment]
BTW, we should add more logs for LLM app workflow, so we can easily understand how it's running, such as:
1. what LLM is using for chat/QA
2. what Embedding is using for retriever
3. what knowledgebase is using for searching 
etc ..

Using log format like "<node-name>: <doing sth> using <LLM/Embedding model>
