### ISSUE TITLE
Clean dependencies of tenx

### ISSUE THREAD

**Issue by huangqg** [kubeagi/arcadia#420]
Clean dependencies of tenx, ensure the opensource projects's compliance.

**Comment by nkwangleiGIT** [comment]
for backend, we only has one dependency for tenx => .github/workflows/graphql_sdk_generate.yml, will update to 
```
-          echo '//dev-npm.tenxcloud.net/:_authToken="${{ secrets.TENX_NPM_TOKEN }}"' >> ~/.npmrc
-          echo '//registry.npmjs.org/:_authToken="${{ secrets.NPM_TOKEN }}"' >> ~/.npmrc
+          echo '//dev-npm.k8s.com.cn/:_authToken="${{ secrets.KUBEAGI_NPM_TOKEN }}"' >> ~/.npmrc
+          echo '//registry.npmjs.org/:_authToken="${{ secrets.KUBEAGI_TOKEN }}"' >> ~/.npmrc
```

**Comment by bjwswang** [comment]
> for backend, we only has one dependency for tenx => .github/workflows/graphql_sdk_generate.yml, will update to
> 
> ```
> -          echo '//dev-npm.tenxcloud.net/:_authToken="${{ secrets.TENX_NPM_TOKEN }}"' >> ~/.npmrc
> -          echo '//registry.npmjs.org/:_authToken="${{ secrets.NPM_TOKEN }}"' >> ~/.npmrc
> +          echo '//dev-npm.k8s.com.cn/:_authToken="${{ secrets.KUBEAGI_NPM_TOKEN }}"' >> ~/.npmrc
> +          echo '//registry.npmjs.org/:_authToken="${{ secrets.KUBEAGI_TOKEN }}"' >> ~/.npmrc
> ```

maybe @Carrotzpc  can help

**Comment by Carrotzpc** [comment]
You can consider forwarding dev-npm.k8s.com.cn to dev-npm.tenxcloud.net

**Comment by nkwangleiGIT** [comment]
we can use http://dev-npm.k8s.com.cn/ now

**Comment by nkwangleiGIT** [comment]
seems graphql_sdk_generate.yml was already removed, mark it as closed
