### ISSUE TITLE
Multiple gpus on different nodes

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#427]
I found a discussion in vllm community about `deploy vllm model across multiple nodes in kubernetes`
https://github.com/vllm-project/vllm/issues/1363

<img width="884" alt="image" src="https://github.com/kubeagi/arcadia/assets/30621793/5f1b7c9a-31de-434f-9a46-d6dd7e5d07cf">

**Comment by bjwswang** [comment]
We may try

- kuberay -> manger gpu cluster
- vllm  -> run ray application(llm models)
- rdam -> IB(infiniBand)

**Comment by nkwangleiGIT** [comment]
Use ray as distributed runtime to support GPU resource pool across nodes, we can run big LLM models using multiple GPUs now.

**Comment by nkwangleiGIT** [comment]
Add docs here: http://kubeagi.k8s.com.cn/docs/category/distributed-inference

**Comment by nkwangleiGIT** [comment]
Fixed by https://github.com/kubeagi/arcadia/pull/500
