### ISSUE TITLE
Data processing - Data lineage support, know how answer is generated

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#430]
Data lineage - 数据血缘，掌握数据的来龙去脉，比如：支持回答与原始文档关系映射

部分参考：
![image](https://github.com/kubeagi/arcadia/assets/8486975/b332e533-c009-421e-8a6d-d48cf65966df)

**Comment by bjwswang** [comment]
@nkwangleiGIT  This requires the `Dataprocessing` provides more details on 

Each `QA` item(line)   ->  Which file chunk ( Line xxx -> Line xxx)

**Comment by nkwangleiGIT** [comment]
@ggservice007 will support this on QA->chunck->file mapping

**Comment by bjwswang** [comment]
@ggservice007  Langchain is using  [unstructured](https://github.com/Unstructured-IO/unstructured/tree/main/unstructured) for pdf loader which should have  metadata included .

**Comment by ggservice007** [comment]
Add the following field to the csv file generated by the data processing.
```cmd
chunk_content
page_number
```

@bjwswang @Abirdcfly

**Comment by bjwswang** [comment]
closed as completed
