### ISSUE TITLE
Data processing - deduplicate Q

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#431]
1. 对大模型生成的 QA 对进行相似度分析，允许用户手动处理（删除、合并等）
2. 提高 Q  的覆盖率，增大召回率（避免有的内容没有被 Q 覆盖），保证 Indexing 阶段可以覆盖所有文本内容、切片

**Comment by nkwangleiGIT** [comment]
https://github.com/whylabs/langkit

https://github.com/whylabs/whylogs

[Text Quality](https://github.com/whylabs/langkit/blob/main/langkit/docs/features/quality.md)
readability score
complexity and grade scores
[Text Relevance](https://github.com/whylabs/langkit/blob/main/langkit/docs/features/relevance.md)
Similarity scores between prompt/responses
Similarity scores against user-defined themes

**Comment by wangxinbiao** [comment]
> 1. 对大模型生成的 QA 对进行相似度分析，允许用户手动处理（删除、合并等）
这一点的允许用户手动处理，跟产品沟通的是准备放到数据集那边做处理。

**Comment by ggservice007** [comment]
We can try two stage search.
1st stage for retrieval embedding

2nd retrieval rerank

reference

https://mp.weixin.qq.com/s/9zJJ4CHyeN75gklIrwQmbw

**Comment by bjwswang** [comment]
rerank recall这些可以在知识库相似性查询部分进行(KnowledgebaseRetriever)  https://github.com/kubeagi/arcadia/blob/main/pkg/appruntime/retriever/knowledgebaseretriever.go#L110

**Comment by bjwswang** [comment]
去重不能直接把重复条目删除，最好是把重复的条目拼接后再次让大模型帮忙生成一段完整的内容

**Comment by bjwswang** [comment]
We can track the `QA qualitiy improving` in another issue.
