### ISSUE TITLE
Reranking- Retrieval and reranking for RAG optimizing

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#434]
* Retrieval
优化 Q，来提高文档切片的召回率 （Question Transformation），重点考虑黑色字体的方式
  * Question Transformation
    Rewrite-Retrieve-Read：使用大模型改写问题； 
    Step Back prompting：使用大模型产生问题的“Step-back Question”，并将问题和Step-back一同用于召回； 
    Follow Up Questions：将历史对话记录融入当前问题进行召回； 
    **Multi Query Retrieval：使用大模型基于原始问题，从不同角度产生多个新问题，并使用每一个新问题进行召回；**
    HyDE[5]：使用大模型产生问题的Hypothetical答案，并将问题和答案一同用于召回。
  * **RAG-Fusion - 结合Multi Query Retrieval 和基于倒数排序融合 Reciprocal Rank Fusion (RRF）**
  * Small-to-Big

* Reranking
Reranking 在切片文档被获取后进行“Postprocessing”，以提升Top_K的精度，降低送往大模型文档切片的噪声
**引入  bge-reranker 模型？**

**Comment by nkwangleiGIT** [comment]
1. 商业模型 - Cohere AI
https://www.pinecone.io/learn/series/rag/rerankers/
2. 开源模型 - bge-reranker
https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/reranker
微调：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/reranker
3. https://github.com/netease-youdao/BCEmbedding

**Comment by bjwswang** [comment]
closed as completed
