### ISSUE TITLE
Ray: a unified framework for scaling AI and Python applications 

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#451]
https://github.com/ray-project/ray

**Comment by nkwangleiGIT** [comment]
Let's start with https://github.com/ray-project/kuberay.

**Comment by nkwangleiGIT** [comment]
Integrate with Ray distributed GPU computing, and use GPU across nodes.
1. Install Ray head node using kuberay
2. Run worker node and join Ray cluster, use GPUs in this Ray cluster's resource pool

**Comment by bjwswang** [comment]
Can be closed now.
