### ISSUE TITLE
Should use QAGenerationChain during data processing

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#483]
Langchain already provides a `QAGenerationChain` https://github.com/langchain-ai/langchain/tree/master/libs/langchain/langchain/chains/qa_generation for generating  QAs via LLM

**Comment by ggservice007** [comment]
@bjwswang  We are using the LangChain 0.1.0 to try this function now.

**Comment by wangxinbiao** [comment]
@ggservice007 @bjwswang 直接使用QAGenerationChain有问题，请查看上面的说明。

**Comment by bjwswang** [comment]
> @ggservice007 @bjwswang 直接使用QAGenerationChain有问题，请查看上面的说明。

Langchain执行的结果是没办法解析么？

**Comment by wangxinbiao** [comment]
> > @ggservice007 @bjwswang 直接使用QAGenerationChain有问题，请查看上面的说明。
> 
> Langchain执行的结果是没办法解析么？ 看起来是有 Q1 和 A1内容的

对，是有Q1和A1的内容，但是它内部是使用json.loads(res[0].text)方式去解析text，而生成的内容不是一个json格式的数据。我试了下用它默认的prompt去生成，生成的内容也不是一个json格式的数据。

**Comment by bjwswang** [comment]
> > > @ggservice007 @bjwswang 直接使用QAGenerationChain有问题，请查看上面的说明。
> > 
> > 
> > Langchain执行的结果是没办法解析么？ 看起来是有 Q1 和 A1内容的
> 
> 对，是有Q1和A1的内容，但是它内部是使用json.loads(res[0].text)方式去解析text，而生成的内容不是一个json格式的数据。我试了下用它默认的prompt去生成，生成的内容也不是一个json格式的数据。

是不是需要适当调整下prompt？

**Comment by wangxinbiao** [comment]
> > > Langchain执行的结果是没办法解析么？ 看起来是有 Q1 和 A1内容的
> > 
> > 
> > 对，是有Q1和A1的内容，但是它内部是使用json.loads(res[0].text)方式去解析text，而生成的内容不是一个json格式的数据。我试了下用它默认的prompt去生成，生成的内容也不是一个json格式的数据。
> 
> 是不是需要适当调整下prompt？

需要调整，我试了QAGenerationChain默认的prompt也是不行。它对prompt的格式要求要高一些。
