### ISSUE TITLE
Log the change sql for the Data process database.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#501]
# version 0.2.0
## sql file

# base

**Comment by wangxinbiao** [comment]
# base
基础sql文件
[base.txt](https://github.com/kubeagi/arcadia/files/13882043/base.txt)

# change
新增的内容
[change.txt](https://github.com/kubeagi/arcadia/files/13882063/change.txt)

**Comment by wangxinbiao** [comment]
# change 20240112
[change-20240112.txt](https://github.com/kubeagi/arcadia/files/13911011/change-20240112.txt)

**Comment by bjwswang** [comment]
@ggservice007 @wangxinbiao  If you want to record the changelogs, you better to make it clear in your Pull Requests  or metains a changelog  in `data-processing/CHANGELOG.md`

**Comment by bjwswang** [comment]
github不适合维护这种要长期开的issue。用changelog要更好

**Comment by bjwswang** [comment]
close as discussed

**Comment by wangxinbiao** [comment]
# change 20240112

[change_20240226.txt](https://github.com/kubeagi/arcadia/files/14400887/change_20240226.txt)

**Comment by wangxinbiao** [comment]
# change 20240226

[change_20240315.txt](https://github.com/kubeagi/arcadia/files/14633440/change_20240315.txt)
