### ISSUE TITLE
Able to use kubernetes Job as evaluation runner

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#508]
Our evaluation flow will have 3 jobs:

Job1: Download dataset files from our system datasource

- [x] download dataset files for evaluation @0xff-dev 

Job2: Generate ragas test dataset based on the `Stage1` files 

- `arctl eval gen_test_dataset` https://github.com/kubeagi/arcadia/pull/529 @bjwswang 

Job3: Evaluate

- with python ragas https://github.com/kubeagi/arcadia/pull/513 @Lanture1064 
- JudgeLLM uses `OpenAI ChatGPT`  

At the end of this evaluation,we should keep 

- ragas evaluation scores

Job4:  Upload metrics  

- [x] upload metrics to system datasource @Lanture1064 

The overall workflow will be 

![evaluation_jobflow drawio](https://github.com/kubeagi/arcadia/assets/30621793/80fdbdda-1080-4eb0-84c1-37d7d5f117e3)

To implement this evaluation runner,we also need to :

- [x] #566
- [x] matain a evaluatoin runner image

**Comment by nkwangleiGIT** [comment]
the chart of evaluation flow can be added to doc center.

**Comment by bjwswang** [comment]
@0xff-dev @Lanture1064
