### ISSUE TITLE
data processing task : Real-time data access

### ISSUE THREAD

**Issue by GHOSTHSP** [kubeagi/arcadia#512]
# What
   Crawl URL content(text、image、table ... eg) manually or periodically
   
# How
   Web crawling using Playwright. Scheduling was using Kubernetes CronJob   
   
# Goal
   After craw the url content, you can add the content to the knowledge base.

**Comment by ggservice007** [comment]
@GHOSTHSP  please describe how to store the content crawled.

**Comment by bjwswang** [comment]
@ggservice007 @GHOSTHSP any progress ?

**Comment by GHOSTHSP** [comment]
@bjwswang Currently, the website crawling utils and database operation utils have been completed.

**Comment by bjwswang** [comment]
> @bjwswang Currently, the website crawling utils and database operation utils have been completed.

Thanks! To support this,we need to :

- [ ] add a new datasource kind `Web` 
- [ ] able to use `Web` datasource in versioneddataset 
- [ ] able to load/process `Web` files
