### ISSUE TITLE
AI Agent - add more useful context to the session

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#521]
每次做动作的 prompt 会分为四步：
1. Profile 画像
* 初始包括基本信息，比如用户角色、爱好、描述、标签等
* 可以通过检索它的一些特征，或者自己定义它的特征，或者对 LLM 进行微调让 agent 具备相对应特征的能力。
2. 当前的动作是在什么时间发生的
3. 对记忆进行检索，与当前动作可能最相关的记忆
4. Instruction 希望它做什么

**Comment by bjwswang** [comment]
用户画像做的好挺麻烦的，是不是可以放0.5

**Comment by Abirdcfly** [comment]
Inactive for a long time, close the issue
