### ISSUE TITLE
introduce reranker in our knowledgebase retriever 

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#523]
To enhance the relevance of context(retrieved from our knowledgebase),we can do `reraking` on searched documents ( more than top_k )and find the `top_k` documents. 

There are two ways to do reraking:

1. Let a `LLM` decides
2. Use a `reraking model` 

examples:

- [LlamaIndex](https://colemurray.medium.com/enhancing-rag-with-baai-bge-reranker-a-comprehensive-guide-fe994ba9f82a) 

- [langchain with cohere reranker](https://python.langchain.com/docs/integrations/retrievers/cohere-reranker)
- [langchain with pinecone](https://python.langchain.com/docs/templates/rag-pinecone-rerank)

**Comment by nkwangleiGIT** [comment]
reference:
* https://www.pinecone.io/learn/series/rag/rerankers/
* https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/reranker
* https://github.com/netease-youdao/BCEmbedding

**Comment by bjwswang** [comment]
@nkwangleiGIT  reranker requires a different ranking models  comparing to embedding models. The api provided by fastchat can not be used for this reranker. 

So we should write a apiserver  to handle `rerank` requests and use our model repository(minio) to store the reraking model files.  

The task tracked at See https://github.com/kubeagi/core-library/issues/13 

@Abirdcfly Please add more details on how you would like to use this reraking api.

**Comment by Abirdcfly** [comment]
![image](https://github.com/kubeagi/arcadia/assets/5100555/bf1b1617-c4d2-48e9-a4dd-5dc42cd06738)
![image](https://github.com/kubeagi/arcadia/assets/5100555/a63dc133-6680-409f-9893-dd39f07ea0e7)

**Comment by bjwswang** [comment]
@Abirdcfly  It's worthy to decide a reranking model now . Since we use bge for embedding, how about  https://huggingface.co/BAAI/bge-reranker-large#using-flagembedding ?

**Comment by Abirdcfly** [comment]
1. just like `DocumentLoader`, we can add a CRD `rerank` to config rerank model.
2. just like `vectorstore` CRD, user web interface now don't need config `rerank` CRD.
3. Because almost all `rerank` models can be invoked through `transformers`, `app.py` does not need adjustment. For the model download section, we can reuse some of the `model` CRD handling logic.
