### ISSUE TITLE
🐛 `for loop` address problem, resulting in incorrect time

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/arcadia#535]
https://github.com/kubeagi/arcadia/blob/ecccf395c89630fb0403cfc9696ead21fd9e0f19/apiserver/pkg/versioneddataset/versioned_dataset.go#L132

The address of the obj is `constant`, so the time field for all the final data will be the time of the last item.

**Comment by bjwswang** [comment]
is this duplicated to #541  ? @0xff-dev @Abirdcfly

**Comment by 0xff-dev** [comment]
> is this duplicated to #541 ? @0xff-dev @Abirdcfly

Yes.
