### ISSUE TITLE
able to use vllm without ray

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#546]

**Comment by nkwangleiGIT** [comment]
I think it's already supported if we don't configure ray cluster in arcadia-config and have a NUM_GPUS > 1.

**Comment by nkwangleiGIT** [comment]
similar requirement in vllm project: https://github.com/vllm-project/vllm/issues/208

**Comment by bjwswang** [comment]
Thanks @bobsongplus !

**Comment by nkwangleiGIT** [comment]
Actually, vllm is depending on Ray for distributed inference, but we can use vllm without Ray cluster, that's to run vllm on GPU(s) on the single node. So we support to run vllm with embedded Ray cluster(no manual configuration required)
