### ISSUE TITLE
ray cluster head must have  models

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#547]
Now our worker acts as a ray worker which have models files downloaded by a `loader init container`.  If we want to deploy this worker with a ray cluster, we need to upload files to the head container manually which is really complicated.

**Comment by bjwswang** [comment]
Thanks @bobsongplus !

**Comment by bobsongplus** [comment]
the issue is related to the ray project. Issuer: https://github.com/ray-project/kuberay/issues/1753.
Maybe using the latest version of ray will fix the issue: https://github.com/ray-project/ray/pull/41832.

**Comment by bjwswang** [comment]
tested on none predefined ray clusters
