### ISSUE TITLE
support mistral

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#550]
- [ ] https://huggingface.co/mistralai/Mistral-7B-v0.1
- [ ] https://huggingface.co/mistralai/Mixtral-8x7B-v0.1

**Comment by ggservice007** [comment]
Any plan to use Mixtral 8x7B?
@bjwswang 

reference

https://mp.weixin.qq.com/s/jTUZJFjf7qlOPok9VcigYQ

**Comment by bjwswang** [comment]
@ggservice007  That depends on whether `fastchat` supports Misxtral 8x7B .

we don't have this plan yet

**Comment by ggservice007** [comment]
Can not run the Mistral-7B-v0.1 model in our environment. @bjwswang

**Comment by bjwswang** [comment]
`Killed` on 3090. Let me have a try on 4090

**Comment by nkwangleiGIT** [comment]
we can run using Ray cluster, but the QA from Mistral seems weird, probably caused by the prompt(user/system message) defined in langchaingo, don't have the environment to run Mistral for now, let's move this to v0.3.0.

**Comment by nkwangleiGIT** [comment]
we should use the instruct version for chat, refer here for chat template:
https://huggingface.co/docs/transformers/main/chat_templating
models on hugggingface:
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2

**Comment by nkwangleiGIT** [comment]
Tried instruct models, mistral is working normally now, but it seems good at English NLP, not Chinese.
