### ISSUE TITLE
AI Agent - Knowledge Assistant - Create an AI agent that can generate abstract for PDF/Word/web links, and accumulate knowledge

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#553]
Allow user to upload pdf/word or paste web links and then generate a summary, the prompt might be:
* Prompt 示例

1）英文
Provide a summary based on the given content. Output the summary directly without any introductory text. Here is the content: 

{{.question}}

2）中文
需要你根据一段内容写一段摘要，直接输出摘要，不需要提示性文字，内容如下：

{{.question}}

* Required features
1. upload to 微信小程序，and use whole content as {{.question}} if the content is smaller that 10Mi
2. if file is bigger than 10Mi, split it to chunk of paragraphs, then get abstract of each chunk
3. file management, give each user 1G free s3 storage to save user files, and provide upload/delete/download features
5. user can create knowledgebase based on selected files or based on file labels
need content embedding and Q/A embedding?
6. allow to chat/generate article with knowledgebase
7. support to import chat history from wechat, dingtalk, feishu, etc, QQ ...
8. provide APIs to integrate with other tool/product

**Comment by bjwswang** [comment]
- [ ] Use LLM directly 
- [ ] Use LLM with the help of pre-dataprocessing

**Comment by nkwangleiGIT** [comment]
以句为单位来分析文章，然后预测每句话是否包含进摘要里边
参考文章：https://arxiv.org/pdf/1903.10318v2.pdf

**Comment by bjwswang** [comment]
- ref https://medium.com/@johnidouglasmarangon/how-to-summarize-text-with-openai-and-langchain-e038fc922af

**Comment by bjwswang** [comment]
> * ref https://medium.com/@johnidouglasmarangon/how-to-summarize-text-with-openai-and-langchain-e038fc922af
> * langchain summarization https://python.langchain.com/docs/use_cases/summarization

Based on langchian's `MapReduceDocuments`, we can get a concise summary of the pdf.  https://github.com/tmc/langchaingo/blob/main/chains/summarization.go#L54

0. Use text splitter to split large document to chunked documents ,say 32 chunked documents
1. Map:  ask the lllm to summarize the 32 chunked documents ->  32 mapped documents
2. Reduce(StuffDocument): join all 32 mapped documents together as the input ->  output one document


Take `考勤` as an example:

Summary with QWen:

```text
The text describes a method for fine-tuning a language model for a specific task called "AdvertiseGen". The method involves training the model on a large dataset of text data with the same task, and then fine-tuning it on a smaller dataset of text data with the same task. The article also provides code examples and data sets for the AdvertiseGen model and offers tips on the potential drawbacks of fine-tuning a model's distribution, such as reduced generalization and performance, and suggests using general data like ShareGPT to mitigate this issue.
```


### Thoughts

- When we split the document at step 0 ,we can also build a tiny knowledgebase(Embedding) as well. 
- Text ChunkSize matters
- LLM matters 
-  `Summarization` is different with `Abstract` 
......

**Comment by bjwswang** [comment]
Performance by zhipuai:

1. glm-3-turbo
```shell
This is a company memo outlining the guidelines for attendance management, including the purpose, scope, and procedures for recording and reviewing employee attendance. The policy aims to improve work discipline and efficiency, as well as providing a clear basis for the company\'s attendance management. The scope of this policy applies to all full-time and part-time employees, as well as interns. Employees are expected to strictly adhere to work rules and attendance regulations, and department heads are responsible for reviewing and approving employee attendance records. The Human Resource department is responsible for recording, summarizing, and monitoring the execution of this policy.

The policy outlines the consequences for being considered a scab, the procedure for requesting time off for personal reasons, and the standard for attendance. It also specifies the procedure for calculating and granting leave, and the consequences for failing to meet attendance targets. The document outlines the responsibilities of the human resources department for enforcing these rules and providing explanations and clarification.

In summary, this policy outlines the guidelines for attendance management, including the purpose, scope, and procedures for recording and reviewing employee attendance. It aims to improve work discipline and efficiency, and provides a clear basis for the company\'s attendance management.
```

2. glm-4

```shell
This is a company policy regarding attendance management, specifically for the purpose of improving work discipline and efficiency. It applies to all full-time and part-time employees, as well as interns. The policy outlines the responsibilities of departments leaders, the Human Resource department, and the consequences of non-compliance. It also outlines the company\'s work schedule and attendance system, including flexible work hours, shift assignments, and meal breaks.

The policy covers various aspects of employee leave, including vacation time, sick leave, personal reasons for absence, and maternity leave. It also outlines the procedures for requesting and approving leave, as well as the rules and consequences for not following the attendance system and not打卡 or for failing to properly clock in and out.

The policy covers the responsibilities of the HR department for enforcing these rules and specifies that any issues not addressed in the document will be subject to the relevant laws and regulations. It will come into effect on May 1st, 2023.

Overall, this policy aims to regulate and standardize employee leave and vacation policies, and to improve work discipline and efficiency.
```

**Comment by bjwswang** [comment]
Steps t build a `chat with doc`:

1. Create a new conversation with a id
2. Upload files with this conversationid
 - DO NOT SAVE FILE to oss
 - processing(QAGeneration,Embedding,Summary) this pdf in our apiserver when upload file
 - create a `conversation knowledgebase`
 3. Chat with the above `conversation knowledgebase`
 -
