### ISSUE TITLE
agentserver for agent-portal/gptstore

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#568]
Agent-portal provides different features to its users . We'd better to maintain in a new api server. 

We will have two kinds of agents by default:

- https://github.com/kubeagi/arcadia/issues/553
- https://github.com/kubeagi/arcadia/issues/554

Will reuse our apiserver code as much as possible.

Currently langchaingo provides two kinds of agent implementations:

1. MRKL Agent 

- MRKL https://arxiv.org/pdf/2205.00445.pdf
- langchaingo https://github.com/tmc/langchaingo/blob/main/agents/mrkl.go 
- blog: https://cobusgreyling.medium.com/create-a-mrkl-autonomous-agent-using-langchain-openai-serpapi-39664a514459

![image](https://github.com/kubeagi/arcadia/assets/30621793/ebc66a1c-87f3-4bca-80d7-ae8a5fc308c1)

2. Conversational Agent

- langchaingo https://github.com/tmc/langchaingo/blob/main/agents/conversational.go

**Comment by nkwangleiGIT** [comment]
whether we need a separate apiserver for GPTs, we can decide later when we have more experience.
