### ISSUE TITLE
take a look at aiconfig, some good features we can refer to

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#577]
https://github.com/lastmile-ai/aiconfig

Wizard GPT - a Wizard chat app
[Prompt Routing](https://github.com/lastmile-ai/aiconfig/tree/main/cookbooks/Basic-Prompt-Routing)
[Multi-LLM Consistency](https://github.com/lastmile-ai/aiconfig/tree/main/cookbooks/Multi-LLM-Consistency)
[Safety Guardrails for LLMs - LLama Guard](https://github.com/lastmile-ai/aiconfig/tree/main/cookbooks/LLaMA-Guard)
[Chain-of-Verification](https://github.com/lastmile-ai/aiconfig/tree/main/cookbooks/Chain-of-Verification)

**Comment by krrishdholakia** [comment]
Hey @nkwangleiGIT @bjwswang, I'm the maintainer of [litellm](https://github.com/BerriAI/litellm) - an openai proxy server to safely call 100+ LLMs. 

**We support LlamaGuard** - https://docs.litellm.ai/docs/proxy/enterprise#content-moderation-with-llamaguard

Would this be helpful? Happy to make a PR, if so

**Comment by bjwswang** [comment]
closed as we can do further research later
