### ISSUE TITLE
Should not allow to delete resources if they are being used 

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#598]
- [ ] Should not allow to delete Model if it is being used by Worker
- [ ] Should not allow to delete  Worker/LLM/Embedder if it is being used by Application
- [ ] Should not allow to delete knowledgebase if it is being used by Application
...

@liutianyi0801 any comments?

**Comment by liutianyi0801** [comment]
这个在此前的 bug 中提到过：
1、如果 Worker/LLM/Embedder 正在被使用（Agent 、数据处理任务），则不允许下线/删除，正在被使用的删除按钮禁用，hover 提示原因
2、如果 知识库 正在被 Agent 使用 ，则不允许删除


Worker 与模型文件是强关联的么？

**Comment by nkwangleiGIT** [comment]
we can improve this in latter release, reopen and move to v0.5.0
