### ISSUE TITLE
🌱 The VersionedDataset supports getting file information based on a specific list of files.

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/arcadia#643]

**Comment by bjwswang** [comment]
@0xff-dev please provide more details .

**Comment by 0xff-dev** [comment]
Currently only allows paging the files of the dataset, filtering based on keywords, **but there may be the possibility of getting a specific specified few files.**

**Comment by bjwswang** [comment]
no this requirement for now. we can reopen it when we need this.
