### ISSUE TITLE
🚀  Add api to support copying existing rag

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/arcadia#700]
Copy a new rag based on the name of an existing rag.

**Comment by bjwswang** [comment]
@0xff-dev we can do this in next version

**Comment by 0xff-dev** [comment]
A label can be added to the newly created RAG indicating that the newly created RAG was copied from that RAG.

**Comment by bjwswang** [comment]
> A label can be added to the newly created RAG indicating which RAG the newly created RAG was copied from.

Good idea!

**Comment by dayuy** [comment]
Hi!
