### ISSUE TITLE
Integrate with new LLMs

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#724]
1. Large World Model
https://github.com/LargeWorldModel/LWM

2. The official implementation of Latte: Latent Diffusion Transformer for Video Generation.
https://github.com/Vchitect/Latte

**Comment by bjwswang** [comment]
Anotther video generation llm mentioned in LVM : https://github.com/PKU-YuanGroup/Video-LLaVA

**Comment by bjwswang** [comment]
- https://huggingface.co/google/gemma-7b

**Comment by bjwswang** [comment]
now we support most of popular llms which is good enough. we can reopen this if we need more.
