### ISSUE TITLE
Support Gemma.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#743]
# what
Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models. 

# hugging face
https://huggingface.co/google/gemma-7b

# online try
https://huggingface.co/spaces/Omnibus/google-gemma

# reference
https://mp.weixin.qq.com/s/fpKW9UV7_S-FiFhiIet82g

**Comment by bjwswang** [comment]
@ggservice007 Duplicated with #739

**Comment by bjwswang** [comment]
@Lanture1064  Seems fastchat support this gemma now . Please verify it .

**Comment by bjwswang** [comment]
closed since fastchat support

**Comment by nkwangleiGIT** [comment]
Gemma is supported after fastchat v0.2.36: https://github.com/lm-sys/FastChat/commit/4edbd9d60c19b81e5123477d69eac71b074875cf

So we can add gemma support at the next fastchat release, might be v0.2.37.
