### ISSUE TITLE
Upgrade fastchat to v0.2.36 to support image input

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#748]

**Comment by nkwangleiGIT** [comment]
take care of this issue: https://github.com/lm-sys/FastChat/issues/3067, we need to use pydantic==1.10.14

**Comment by cyberluke** [comment]
> take care of this issue: [lm-sys/FastChat#3043](https://github.com/lm-sys/FastChat/issues/3043) we need to use pydantic==1.10.14

This is still not solved in FastChat 0.2.3.6. I had to downgrade Pydantic.
