### ISSUE TITLE
Agent orchestration optimize

### ISSUE THREAD

**Issue by huangqg** [kubeagi/arcadia#759]
1、智能体编排支持全屏模式，智能体详情描述通过右侧弹窗展示，或者精简下内容，目前占位太多，影响智能体的编排空间
2、支持单智能体和多个智能体编排，且切换自然，参考coze的多个智能体编排。如下图
3、智能体设计需归类符合智能体的理论组成结构，四大模块：Profile（配置）、Memory（记忆）、Planning（规划）、Action（执行）等，参考下图
4、多智能体编排
5、参考最下图产品原型

![image](https://github.com/kubeagi/arcadia/assets/5961349/6abd1cb6-06f8-4550-9bbc-b53547abb9d7)

![image](https://github.com/kubeagi/arcadia/assets/5961349/3e2b10b1-b48a-42a3-8173-db48b0692348)
coze 多agent

![image](https://github.com/kubeagi/arcadia/assets/5961349/31b13a79-8980-4064-b8e8-fd09867096f4)

![image](https://github.com/kubeagi/arcadia/assets/5961349/0460787f-f110-408c-a7a5-d1a02a2f7ec6)

![image](https://github.com/kubeagi/arcadia/assets/5961349/00afa098-0e5f-4c40-98a8-b89b16fa72fa)

![image](https://github.com/kubeagi/arcadia/assets/5961349/2dff9d27-d5a0-4280-a1e6-fed8caaacfd3)
修改后原型

**Comment by huangqg** [comment]
智能体编排可以只保留全屏模式，不需要导航栏和左侧栏。

**Comment by bjwswang** [comment]
@liutianyi0801

**Comment by huangqg** [comment]
close this issue as it's finished.
