### ISSUE TITLE
missing https://pypi.org/project/transformers-stream-generator/  in our fastchat-worker:v0.2.36

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#797]
When trying to chat with the worker(deployed with v0.2.36), nothing got returned. When running qwenb,a error found which says it do not have the transformers-stream-generator.

**Comment by 0xff-dev** [comment]
This dependency is installed in the dockerfile

https://github.com/kubeagi/arcadia/blob/ac3a6d297403c872ec331abf761a1a1169f6ee37/deploy/llms/Dockerfile.fastchat-worker#L37

**Comment by bjwswang** [comment]
@0xff-dev Well... then seems the image utilized yesterday is not the right one.
