### ISSUE TITLE
worker api returns 400 Bad request frequently

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#820]

**Comment by nkwangleiGIT** [comment]
I used qwen1.5-7b this morning, and didn't see 400 error for now, seems it's also related to the load of GPU to cause 400 error(maybe multiple users cause cocurrent load)

**Comment by nkwangleiGIT** [comment]
seems this commit fix this 400 issue:
https://github.com/kubeagi/arcadia/commit/dd2417ae86bd3484b7a0ff72443886efbc6a5164
increase the value of streaming timeout
