### ISSUE TITLE
should let the user configure bingkey in their applicaiton

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#825]
Since bingkey costs money, we should let user configure the bingkey at section `applicaiton's tools`

**Comment by Abirdcfly** [comment]
now, user can config 
see  https://github.com/kubeagi/arcadia/blob/13a21ff7e916a51ddd706acae8d51b8ad2667072/config/samples/app_llmchain_chat_with_bot_tool.yaml#L101-L116

and apiserver to gql has export this config
https://github.com/kubeagi/arcadia/blob/13a21ff7e916a51ddd706acae8d51b8ad2667072/apiserver/graph/schema/entrypoint.graphqls#L79-L107

**Comment by bjwswang** [comment]
please remove the apikey in our apiserver env

**Comment by Abirdcfly** [comment]
emm...Weather Query API apikey also need remove...
