### ISSUE TITLE
Verify the performance of data processing, such as how long it takes to process a 1MB-sized PDF.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#836]
# what
Verify the performance of data processing, such as how long it takes to process a 1MB-sized PDF.

**Comment by bjwswang** [comment]
> # what
> Verify the performance of data processing, such as how long it takes to process a 1MB-sized PDF.

| Model |  GPU | FileSize  | TimeCost |
| qwen-7b-chat | 4090 | 1MB | xxx |

**Comment by wangxinbiao** [comment]
Model   |   FileSize   |   TimeCost
------   |   --------   |   ---------
qwen-1.5-7b-chat   |   1.5M   |   13min35s
