### ISSUE TITLE
Verify the functionality of data processing and knowledge base through a PDF file with the two layouts in one page.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#843]
# what
Verify the functionality of data processing and knowledge base through a PDF file with the two layouts in one page.

# example
![img_v3_028v_72ac6b1d-c136-471a-9ee9-51e376978dag](https://github.com/kubeagi/arcadia/assets/9192908/90c0b24a-6c68-4794-bd1e-d35a7874afef)

**Comment by nkwangleiGIT** [comment]
It's verified and supported by pdftotext.
