### ISSUE TITLE
Verify the functionality of data processing and knowledge base features using an English-language academic paper.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#844]
# what
Verify the functionality of data processing and knowledge base features using an English-language academic paper.

# result
## blank space
Sometime has blank space.

![image](https://github.com/kubeagi/arcadia/assets/9192908/a5978a38-8612-4e41-98d7-ed88ee182cd6)

**Comment by nkwangleiGIT** [comment]
There is no such kind of issue using https://github.com/sajari/docconv, and we can use LLM to refine/fix the wrong words to make it more accurate.
