### ISSUE TITLE
Should we maintain the dedicated ragas_once tool, or update eval image to use core-library?

### ISSUE THREAD

**Issue by Lanture1064** [kubeagi/arcadia#849]
Ragas_once tool has been copied into https://github.com/kubeagi/core-library and updated to match langchain 0.1.x and ragas 0.1.x. But the eval image is still using the old code here. Should we maintain the dedicated version here, or build a new eval image to use codes in core-library?

**Comment by bjwswang** [comment]
we should migrate our image to `kubeagi/core-library-cli` . You can have a test on the new image with `kubeagi-cli eval`
