### ISSUE TITLE
When generating a QA (Question and Answer) list, the maximum number of QA pairs should be dynamically calculated based on the prompt, rather than being fixed.

### ISSUE THREAD

**Issue by ggservice007** [kubeagi/arcadia#853]
# what
When generating a QA (Question and Answer) list, the maximum number of QA pairs should be dynamically calculated based on the prompt, rather than being fixed.

In the current LLMs (Large Language Models), the values of tokens are relatively large. For instance, qwen 1.5 has a limit of 32k, while models like Yi can handle up to 200k.  So wen can set chunk size to a large number.

## for example

|token size|QA number|
|--|--|
|500|25|
|1000|50|
|2000|100|
|...|...|

**Comment by bjwswang** [comment]
Since we allow user to customize their prompt, use can modify `no more than 25` .
