### ISSUE TITLE
VersionedDatasetQuery.getVersionedDataset should support files pagination input

### ISSUE THREAD

**Issue by Carrotzpc** [kubeagi/arcadia#863]
![image](https://github.com/kubeagi/arcadia/assets/10265417/f8f20427-0fcb-4153-a0b9-d81f851c2ca8)

**Comment by 0xff-dev** [comment]
The files field in the data returned by versioneddataset is a resolver that supports paging of files.

**Comment by 0xff-dev** [comment]
https://github.com/kubeagi/arcadia/blob/18a3a999cd494009560ba412355d7e93b3e43736/apiserver/graph/schema/versioned_dataset.gql#L50
