### ISSUE TITLE
agile-gpt UI issues

### ISSUE THREAD

**Issue by huangqg** [kubeagi/arcadia#931]
UI issues

![image](https://github.com/kubeagi/arcadia/assets/5961349/dac12926-a15a-4201-b9d5-40bd02958b7f)

未登录状态需要设计下，这里显示像加载失败
![image](https://github.com/kubeagi/arcadia/assets/5961349/a31396e1-eca2-4747-8bc2-9a4e78bbc290)

**Comment by bjwswang** [comment]
@liutianyi0801

**Comment by liutianyi0801** [comment]
已解决
