### ISSUE TITLE
The problems list after upgrade system

### ISSUE THREAD

**Issue by huangqg** [kubeagi/arcadia#963]
## 升级步骤：

1. 更新好values.yaml后，直接 helm upgrade -n kubeagi-system arcadia . ， 提示minio pvc 方面的报错
2. 手动逐个更新镜像，apiserver、ccontroller、opsconsole、agentportal
3. 更新crd：kubectl apply -f crds/

## 升级后问题如下

1、模型文件介绍内容为空，之前有 Readme.md 文件。

![image](https://github.com/kubeagi/arcadia/assets/5961349/2d61d87c-5cfb-43cb-8f0a-cee1128e70af)

查看后台日志
```
kubectl logs arcadia-apiserver-5f5bb5468-kjpx4  -n kubeagi-system -f
E0330 01:52:21.011884       1 minio_server.go:591] stat file poemsai/model/qwen1.5-4b-chat/README.md error The specified key does not exist.
[GIN] 2024/03/30 - 02:04:16 | 500 |   21.897069ms |       127.0.0.1 | GET      "/bff/model/files/stat?fileName=README.md&bucket=kubeagi-system&bucketPath=model%2Fqwen1.5-4b-chat"
```

2、编辑智能体，未读取原有数据，内容为空
![image](https://github.com/kubeagi/arcadia/assets/5961349/49658eb4-0033-4396-b5f8-1db3155df03d)

3、智能体详情页，编辑智能体，能读取原有数据，但分类和从智能体首页编辑智能体的分类不一致，仍为老的分类列表，未从 configmap 读取。两处编辑智能体须一致，或者去掉从智能体首页编辑，避免不一致带来bug。
![image](https://github.com/kubeagi/arcadia/assets/5961349/745049b7-80ea-4935-bddc-e7476459969c)

4、数据源详情，在线数据输入长URL，页面显示有问题
![image](https://github.com/kubeagi/arcadia/assets/5961349/594260e2-724e-41e5-9912-5251efe9beaf)

5、推荐/取消推荐功能失败
#### 以admin用户登录能正常操作，以非admin登录操作会遇到此问题，需注意下用户权限
![image](https://github.com/kubeagi/arcadia/assets/5961349/92c2d020-a288-42f9-a232-afb4403d20c8)

```
{
  "message": "applications.arcadia.kubeagi.k8s.com.cn \"mianshi\" is forbidden: User \"kubeagi\" cannot update resource \"applications\" in API group \"arcadia.kubeagi.k8s.com.cn\" in the namespace \"poemsai\"",
  "path": [
    "Application",
    "updateApplication"
  ]
}
```

**Comment by bjwswang** [comment]
@liutianyi0801 问题4和5已经在ops-console开了issue，追踪下

**Comment by bjwswang** [comment]
问题1传参有问题，需要前后端统一下，@liutianyi0801 @0xff-dev

**Comment by bjwswang** [comment]
@liutianyi0801  这些问题是否修复了？ 如果已经修复，可以关闭issue

**Comment by huangqg** [comment]
@bjwswang @liutianyi0801 除了问题1，其他问题已解决。

**Comment by huangqg** [comment]
cool, the above problems are fixed.
