### ISSUE TITLE
take 9seconds to search references during chat

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#971]
@ggservice007 Please provide more details about this problem

**Comment by ggservice007** [comment]
# how to trace
```shell
kubectl logs -n kubeagi-system arcadia-fastchat-65dbfd7dfc-457c5 -c fastchat-api-server
```

![img_v3_029h_4dfe8291-077d-4d06-b772-6c1a4e1e9a7g](https://github.com/kubeagi/arcadia/assets/9192908/4dbabc52-b4c8-45bf-908a-a804266a84d1)

## step
### step 1 
embedding

### step 2
query the pg vector

This step takes about 7 ~ 9 seconds.

### step 3
invoke llm to generate the answer
